networks:
  appnet:
    external: true
    name: app-network
services:
  es-writer:
    build: .
    container_name: es-writer
    networks: [appnet]
    env_file:
      - .env
    restart: unless-stopped
    # на всякий — явно фиксируем единственную реплику (compose всё равно поднимет одну)
    deploy:
      replicas: 1