apiVersion: apps/v1
kind: Deployment
metadata:
  name: eswriter
  namespace: {{ .Values.namespace }}
  labels:
    app: eswriter
spec:
  replicas: {{ .Values.eswriter.replicas }}
  selector:
    matchLabels:
      app: eswriter
  template:
    metadata:
      labels:
        app: eswriter
      {{- with .Values.eswriter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.eswriter.serviceAccountName }}
      serviceAccountName: {{ .Values.eswriter.serviceAccountName }}
      {{- end }}
      containers:
        - name: eswriter
          image: "{{ .Values.images.eswriter.repository }}:{{ .Values.images.eswriter.tag }}"
          imagePullPolicy: {{ .Values.images.eswriter.pullPolicy }}
          {{- if .Values.eswriter.command }}
          command: {{- toYaml .Values.eswriter.command | nindent 12 }}
          {{- end }}
          {{- if .Values.eswriter.args }}
          args: {{- toYaml .Values.eswriter.args | nindent 12 }}
          {{- end }}

          # Воркерам порт не нужен. Уберите, если он не используется совсем.
          # ports:
          #   - name: metrics
          #     containerPort: 9100

          env:
            # URL очереди и прочие секреты — из Secret
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            # Если ES используется — берём из ConfigMap
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: ELASTICSEARCH_URL
          {{- if .Values.eswriter.extraEnv }}
          {{- toYaml .Values.eswriter.extraEnv | nindent 10 }}
          {{- end }}

          # Пробы для воркера обычно exec или tcp к брокеру. Сделал опционально.
          {{- if .Values.eswriter.probes.enabled }}
          livenessProbe:
            {{- toYaml .Values.eswriter.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.eswriter.probes.readiness | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.eswriter.resources | nindent 12 }}

          # Корректное завершение, чтобы воркер обработал сообщение и вышел
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 5"]
      terminationGracePeriodSeconds: {{ default 30 .Values.eswriter.terminationGracePeriodSeconds }}
      {{- with .Values.eswriter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eswriter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eswriter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
