apiVersion: apps/v1
kind: Deployment
metadata:
  name: eswriter
  namespace: {{ .Values.namespace }}
  labels:
    app: eswriter
spec:
  replicas: {{ default 1 .Values.eswriter.replicas }}
  selector:
    matchLabels:
      app: eswriter
  template:
    metadata:
      labels:
        app: eswriter
      {{- with .Values.eswriter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.eswriter.serviceAccountName }}
      serviceAccountName: {{ .Values.eswriter.serviceAccountName }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: eswriter
          image: "{{ .Values.images.eswriter.repository }}:{{ .Values.images.eswriter.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.images.eswriter.pullPolicy }}

          {{- with .Values.eswriter.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.eswriter.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          # У воркера обычно нет входящих портов. Оставлено на случай метрик:
          {{- with .Values.eswriter.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          # Обязательные/общие переменные окружения
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: ELASTICSEARCH_URL
          {{- with .Values.eswriter.extraEnv }}
          {{- if . }}
          envFrom:
            {{- if .configMaps }}
            {{- range .configMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .secrets }}
            {{- range .secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}

          {{- $probes := .Values.eswriter.probes | default dict }}
          {{- if and $probes ($probes.enabled | default false) }}
          {{- with $probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          resources:
            {{- toYaml ( .Values.eswriter.resources | default dict ) | nindent 12 }}

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 5"]

      terminationGracePeriodSeconds: {{ default 30 .Values.eswriter.terminationGracePeriodSeconds }}

      {{- with .Values.eswriter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.eswriter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.eswriter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
