apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | quote }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
