apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.web.secrets.SECRET_KEY | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.web.secrets.DJANGO_SUPERUSER_PASSWORD | quote }}
