apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector: { app: web }
  ports:
    - name: http
      port: {{ .Values.web.port | default 80 }}
      targetPort: {{ .Values.web.targetPort | default 8000 }}
