apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector: { app: web }
  ports:
    - port: 80
      targetPort: {{ .Values.web.port }}
