apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "santiway.fullname" . }}-eswriter-env
  labels:
    {{- include "santiway.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.eswriter.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
