FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование проекта
COPY . .

# Установка дополнительных утилит для мониторинга (опционально)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Запуск Celery worker
CMD ["celery", "-A", "SantiWayWEB", "worker", "--loglevel=info", "-Q", "apkget"]