# Generated by Django 4.2.25 on 2025-10-07 06:06

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False, verbose_name="оплачено")),
                (
                    "export_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exports/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "json", "zip"]
                            )
                        ],
                    ),
                ),
                (
                    "export_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В обработке"),
                            ("READY", "Готов"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "monitored_macs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
