networks:
  appnet:
    external: true
    name: app-network

services:
  polygon-data-gen:
    build: .
    container_name: polygon-data-gen
    networks: [appnet]
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      replicas: 1

