{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "santiway.fullname" . }}-rabbit
  labels:
    {{- include "santiway.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc }}
  password: {{ include "santiway.existingOrRandomPass" (dict "ns" .Release.Namespace "name" (printf "%s-rabbit" (include "santiway.fullname" .)) "key" "password" "provided" .Values.rabbitmq.auth.password) | b64enc }}
{{- end }}
