# Generated by Django 4.2.24 on 2025-10-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название полигона"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("geometry", models.JSONField(verbose_name="Геометрия полигона")),
                (
                    "area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Площадь (кв.км)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polygons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Полигон",
                "verbose_name_plural": "Полигоны",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolygonAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("device_search", "Поиск устройств"),
                            ("mac_monitoring", "Мониторинг MAC-адресов"),
                            ("anomaly_detection", "Поиск аномалий"),
                        ],
                        max_length=50,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Параметры действия"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("paused", "Приостановлен"),
                            ("stopped", "Остановлен"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID задачи Celery",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Запущен"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "polygon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="polygons.polygon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие полигона",
                "verbose_name_plural": "Действия полигонов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="polygonaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["running", "pending"])),
                fields=("polygon", "action_type"),
                name="uniq_active_action_per_polygon_type",
            ),
        ),
    ]
