namespace: santiway

global:
  imageRegistry: ghcr.io
  security:
    allowInsecureImages: true

images:
  web:
    repository: ghcr.io/iudicio/santiway-web
    tag: "latest"
    pullPolicy: IfNotPresent
  vendor:
    repository: ghcr.io/iudicio/santiway-vendor
    tag: "latest"
    pullPolicy: IfNotPresent
  eswriter:
    repository: ghcr.io/iudicio/santiway-eswriter
    tag: "latest"
    pullPolicy: IfNotPresent

env:
  # общие переменные из вашего .env.example
  DJANGO_SECRET_KEY: "change-me"
  DEBUG: "true"
  ALLOWED_HOSTS: "*,localhost,127.0.0.1"
  # URL очереди для сервисов:
  RABBITMQ_URL: "amqp://celery:celerypassword@santiway-rabbitmq:5672//"
  # если используете Elasticsearch — добавьте сюда адрес
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  DATABASE_URL: "postgresql://santi:santi@santiway-postgresql:5432/santi"

web:
  replicas: 1
  port: 80            
  targetPort: 8000
  env:
    - name: UVICORN_HOST
      value: "0.0.0.0"
    - name: UVICORN_PORT
      value: "8000"
  resources: {}
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: localhost
        paths:
          - path: /
            pathType: Prefix
    tls: []  # для локалки можно без TLS

vendor:
  replicas: 1
  resources: {}

eswriter:
  replicas: 1
  resources: {}
  probes:
    enabled: false

rabbitmq:
  image:
    registry: ghcr.io
    repository: bitnami/rabbitmq
  persistence:
    enabled: true
    storageClass: "hostpath"
    size: 1Gi

postgresql:
  image:
    registry: ghcr.io
    repository: bitnami/postgresql
  primary:
    persistence:
      enabled: true
      storageClass: "hostpath"
      size: 2Gi
  volumePermissions:
    enabled: true
    image:
      registry: ghcr.io
      repository: bitnami/os-shell
