{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "santiway.fullname" . }}-postgres
  labels:
    {{- include "santiway.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "santiway.fullname" . }}-postgres
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: {{ include "santiway.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "santiway.fullname" . }}-postgres
        {{- include "santiway.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "santiway.fullname" . }}-postgres
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: {{ include "santiway.fullname" . }}-postgres, key: username } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ include "santiway.fullname" . }}-postgres, key: password } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: {{ include "santiway.fullname" . }}-postgres, key: database } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec: { command: ["pg_isready","-U","postgres"] }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
      volumes: []
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storageClassName }}
        storageClassName: {{ .Values.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
{{- end }}
