# Generated by Django 4.2.24 on 2025-09-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='APKBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус сборки')),
                ('app_name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('package_name', models.CharField(max_length=255, verbose_name='Имя пакета')),
                ('version_code', models.IntegerField(default=1, verbose_name='Код версии')),
                ('version_name', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='apk_sources/%Y/%m/%d/', verbose_name='Исходный файл')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='apk_builds/%Y/%m/%d/', verbose_name='Собранный APK')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apk_builds', to='users.apikey', verbose_name='API ключ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apk_builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сборка APK',
                'verbose_name_plural': 'Сборки APK',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='apkbuilder__status_28300e_idx'), models.Index(fields=['user', 'created_at'], name='apkbuilder__user_id_bbc7dc_idx')],
            },
        ),
    ]
