# Generated by Django 4.2.24 on 2025-09-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkbuild',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apks/', verbose_name='APK файл'),
        ),
    ]
