# Generated by Django 4.2.25 on 2025-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkbuilder', '0002_apkbuild_apk_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkbuild',
            name='app_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия приложения'),
        ),
    ]
