# Generated by Django 4.2.25 on 2025-11-11 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_apikey_name_user_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('group_name', models.CharField(db_index=True, max_length=100)),
                ('is_connected', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_connections', to='users.apikey')),
            ],
            options={
                'indexes': [models.Index(fields=['api_key', 'is_connected'], name='notificatio_api_key_ea9e68_idx'), models.Index(fields=['group_name', 'is_connected'], name='notificatio_group_n_44d11a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('notif_type', models.CharField(default='INFO', max_length=16)),
                ('coords', models.JSONField(blank=True, default=dict)),
                ('binary_types', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered (ACK)'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.apikey')),
            ],
            options={
                'indexes': [models.Index(fields=['api_key', 'status'], name='notificatio_api_key_478adc_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
