# Generated by Django 4.2.25 on 2025-11-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsconnection',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='wsconnection',
            index=models.Index(fields=['api_key', 'device_id'], name='notificatio_api_key_08b2db_idx'),
        ),
        migrations.AddConstraint(
            model_name='wsconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_connected', True), models.Q(('device_id', None), _negated=True), models.Q(('device_id', ''), _negated=True)), fields=('api_key', 'device_id'), name='uniq_live_ws_per_device'),
        ),
    ]
