name: CI Pipeline

on:
  push:
    branches: [ docker-ci/cd ]
  pull_request:
    branches: [ docker-ci/cd ]

jobs:
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.1 black==24.8.0 isort==5.13.2 bandit safety

      - name: Code formatting check (Black)
        run: |
          black --version
          black --check --diff .

      - name: Import sorting check (isort)
        run: |
          isort --version-number
          isort --check-only --diff .

      - name: Linting (Flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Security check (Bandit)
        run: bandit -r . -ll

      - name: Dependency vulnerability check (Safety)
        run: safety check --short-report

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: santiway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max